# Basic Python

## 1. Split this string

In [ ]:
s = "Hi there Sam!"

In [1]:
s="Hi I am Reshma"

## 2. Use .format() to print the following string. 

### Output should be: The diameter of Earth is 12742 kilometers.

In [ ]:
planet = "Earth"
diameter = 12742

In [2]:
planet="Saturn"
diameter=116460

## 3. In this nest dictionary grab the word "hello"

In [ ]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}

In [5]:
[1,2,3,'hello']

[1, 2, 3, 'hello']

# Numpy

In [ ]:
import numpy as np

## 4.1 Create an array of 10 zeros? 
## 4.2 Create an array of 10 fives?

In [6]:
import numpy as np
array=np.zeros(10)
print("an array of 10 zeros:")
print(array)

an array of 10 zeros:
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]

In [7]:
import numpy as np
array=np.ones(10)*5
print("an array of 10 fives:")
print(array)

an array of 10 fives:
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]

## 5. Create an array of all the even integers from 20 to 35

In [9]:
import numpy as np
array=np.arange(20,36,2)
print("array of all the even integer from 20 to 35")
print(array)

array of all the even integer from 20 to 35
[20 22 24 26 28 30 32 34]

## 6. Create a 3x3 matrix with values ranging from 0 to 8

In [11]:
import numpy as np
import pandas as pd
import numpy as np
x =  np.arange(2, 11).reshape(3,3)
print(x)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]

## 7. Concatenate a and b 
## a = np.array([1, 2, 3]), b = np.array([4, 5, 6])

In [12]:
[1,2,3,4,5,6]

[1, 2, 3, 4, 5, 6]

# Pandas

## 8. Create a dataframe with 3 rows and 2 columns

In [ ]:
import pandas as pd

## 9. Generate the series of dates from 1st Jan, 2023 to 10th Feb, 2023

## 10. Create 2D list to DataFrame

lists = [[1, 'aaa', 22],
         [2, 'bbb', 25],
         [3, 'ccc', 24]]

In [ ]:
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]